version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "3030:3030"
    depends_on:
      - db
    volumes:
      - .:/var/www
    command: php -S 0.0.0.0:3030 -t public

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: a_tower
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u user -password"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  migrations:
    build:
      context: .
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www
    command: php /var/www/database/migrations.php

  set-data:
    build:
      context: .
    depends_on:
      migrations:
        condition: service_completed_successfully
      app:
        condition: service_started
    volumes:
      - .:/var/www
    command: php /var/www/checkIfSensorWork.php

  set-data-2:
    build:
      context: .
    depends_on:
      migrations:
        condition: service_completed_successfully
      app:
        condition: service_started
    volumes:
      - .:/var/www
    command: php /var/www/setSensorData.php

volumes:
  db_data:
